site_name: MultiCrafter Lib
repo_url: https://github.com/liplum/MultiCrafterLib
repo_name: MultiCrafter
theme:
  name: material
  logo: icon.png
  custom_dir: overrides
  favicon: favicon.png
  icon:
    repo: fontawesome/brands/github
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 66 # p
    search: 83   # s
  features:
    - navigation.tabs
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

#page tree
nav:
  - Home:
      - Overview: index.md
      - Troubleshooting: troubleshooting.md
      - Migration Guide: migration.md
  - Usage:
      - JSON & Javascript: usage/json.md
      - Java: usage/java.md
  - Customize:
      - Menu Style: customize/menu.md
      - Built-in: customize/builtin.md
      - Drawer: customize/drawer.md
  - API:
      - MultiCrafter: api/multicrafter.md
      - Drawer: api/drawer.md

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - md_in_html
  - meta
  - toc:
      permalink: "#"
